version: 2
updates:
  - package-ecosystem: "pip"
    assignees: ["blixten85"]
    directories:
      - "/"
      - "/alerts"
      - "/api"
      - "/fetcher"
      - "/scraper"
      - "/webui"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "Europe/Stockholm"
    groups:
      pip-patch-minor:
        update-types: ["minor", "patch"]

  - package-ecosystem: "docker"
    assignees: ["blixten85"]
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:30"
      timezone: "Europe/Stockholm"

  - package-ecosystem: "github-actions"
    assignees: ["blixten85"]
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Europe/Stockholm"
    groups:
      actions-patch-minor:
        update-types: ["minor", "patch"]
