#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

_clear
printf '\n%s%s  Produkter · credential/provider prerequisite wizard%s\n' "$BOLD" "$BLUE" "$RESET"
printf '%s  Host/Docker och Cloudflare verifieras separat. Inga secretvärden samlas in.%s\n\n' "$DIM" "$RESET"
pause "Ready to verify Produkter provider state?"

stage "Host/Docker · encryption + session"
say "Verifiera hostens obligatoriska persistenta secrets utan att läsa ut dem."
open_url "http://localhost:5050/"
step "Verifiera i hostens secret/.env-hantering att PROVIDER_CONFIG_MASTER_KEY och FLASK_SECRET_KEY finns och är persistenta över restart."
step "Starta/restarta den ordinarie appcontainern. Den ska starta utan 'Missing encryption key' eller saknad FLASK_SECRET_KEY."
step "Öppna Inställningar och verifiera att redan sparad krypterad providerkonfiguration kan läsas efter restart. Detta är funktionellt bevis för rätt PROVIDER_CONFIG_MASTER_KEY."
step "FLASK_SECRET_KEY ska vara stabil över restart. Om en befintlig giltig session förväntas överleva, verifiera att den gör det; annars markera endast 'konfigurerad', inte funktionellt bevisad."
step "Om GITHUB_ERROR_REPORT_TOKEN används måste GITHUB_ERROR_REPORT_REPOSITORY också vara satt. Skapa ingen PAT enbart för wizarden."
if ! confirm "Är hostens required secrets stabila och är krypterad providerconfig läsbar?"; then
  warn "Host credential prerequisite är inte verifierad."
  exit 2
fi

stage "AI provider credentials"
say "Verifiera minst en faktisk AI-provider som installationen använder."
open_url "http://localhost:5050/"
step "Öppna Inställningar/Beskriv-verktyg och verifiera konfigurerad providerordning samt minst en aktiv credential för Anthropic, OpenAI, Gemini eller Azure OpenAI."
step "Kör appens befintliga providerverifiering eller en avsiktligt bounded normal testrequest. Detta kan använda providerquota/kosta pengar; gör ingen masskörning."
step "För Azure: verifiera även endpoint + deployment. Enbart API-key räcker inte."
if ! confirm "Har minst en avsedd provider genomfört en riktig lyckad providerrequest?"; then
  warn "Providercredentialen är inte verifierad av enbart sparad config."
  exit 2
fi

stage "Ingest · Secrets Store + external fetcher"
say "Verifiera att app, engine och den externa fetchern använder samma befintliga ingestcredential."
open_url "https://dash.cloudflare.com/"
step "Verifiera account-level secret INGEST_API_KEY med workers-scope samt Secrets Store-binding INGEST_API_KEY_STORE på både produkter-app och produkter-motor."
step "Verifiera Access Bypass endast för engine-maskinrutterna /jobs/lease och /jobs/*/result; övrig engine-trafik ska behålla Access-skydd."
step "På fetcher-hosten: verifiera ENGINE_URL och INGEST_API_KEY i dess lokala secret/.env-hantering utan att visa värden."
step "Kräv evidens från en verklig lyckad fetcher lease/result-cykel efter senaste ingest-key-rotation. GET /health är uttryckligen inte credentialbevis eftersom /health är publik."
if ! confirm "Finns end-to-end-evidens för fetcher → engine med aktuell INGEST_API_KEY?"; then
  warn "Ingestcredentialen är overifierad tills en riktig maskinrequest lyckas."
  exit 2
fi

stage "Cloudflare live deployment state"
say "Verifiera de tre Worker-enheternas live bindings utan att återskapa dem."
open_url "https://dash.cloudflare.com/"
step "Verifiera production Workers produkter, produkter-motor och produkter-bearbetare samt deras avsedda D1/KV/R2/Queue/Service/AI/Secrets Store-bindings."
step "CLOUDFLARE_DEPLOYMENT_CONFIG är endast portabel build/self-hosted config och får inte ligga som Worker runtime-secret."
step "Managed main-build ska rekonstruera production-config från provider-state och bevara bindings via keep_vars/keep_bindings; discovery får inte auto-provisionera resurser."
step "Läs appUrl och engineUrl från den installationsspecifika deployment-state som production verifier använder (lokal cloudflare/deployment.json eller motsvarande live/build-state) och öppna dessa exakta HTTPS-origins."
step "Verifiera appens publika productioningress samt engine /health enligt repositoryts production verifier. Dessa kontroller bevisar liveness, inte ingest-auth."
if ! confirm "Är live Worker-state och publika productionkontroller korrekta?"; then
  warn "Cloudflare runtime-state är overifierad."
  exit 2
fi

stage "Cloudflare Workers Builds · tre deployenheter"
say "Verifiera Workers Builds för app, engine och processor."
open_url "https://dash.cloudflare.com/"
step "Kräv aktuella lyckade main-checks: Workers Builds: produkter, Workers Builds: produkter-motor och Workers Builds: produkter-bearbetare."
step "Verifiera att senaste relevanta main-build använder repositoryts etablerade production commands och att D1-migrationsändringar fortfarande failar stängt från implicit auto-deploy."
step "GitHub Actions ska inte bära en separat Cloudflare deploycredential för normal managed deployment."
if ! confirm "Är alla tre aktuella main Workers Builds-checkar gröna?"; then
  warn "Produkter deployidentitet är overifierad tills alla tre enheter är gröna."
  exit 2
fi

finish
