name: Dependabot merge queue

on:
  schedule:
    - cron: '11 * * * *'
  workflow_dispatch:

permissions: {}

jobs:
  queue:
    uses: Avkroken/.github/.github/workflows/dependabot-automerge.yml@325f7dd521c55fd6d3d8709e49ddef10fbb6bb48
    secrets:
      app-private-key: ${{ secrets.GAMNACKEN_PRIVATE_KEY }}
