name: Dependency review

on:
  pull_request:
    branches: [main]
  merge_group:
    types: [checks_requested]

permissions:
  contents: read

jobs:
  dependency-review:
    uses: Avkroken/.github/.github/workflows/dependency-review-reusable.yml@main
